#!/bin/sh

WG_DIR="/etc/wireguard"
WG_CONF="${WG_DIR}/wg0.conf"
ACCOUNT_JSON="${WG_DIR}/account.json"
ENDPOINT_STATE_FILE="${WG_DIR}/endpoint-state.json"

REGISTER_URL="https://api.cloudflareclient.com/v0a2158/reg"
CF_CLIENT_VERSION="a-6.10-2158"
TRACE_URL_DEFAULT="https://cloudflare.com/cdn-cgi/trace"

TEAMS_TOKEN="${TEAMS_TOKEN:-}"
ENDPOINT_CANDIDATES="${ENDPOINT_CANDIDATES:-}"

# 隧道实现：自研 Rust 重写（warp-rs/），见 docs/module-boundaries.md。
WARP_RS_BIN="${WARP_RS_BIN:-warp-socks-rs}"
# t1/t2 反审查伪装包：Phase 0 验证过 reserved bytes 才是握手必需机制，trick
# 本身不是必需项，默认关闭更快；保留开关应对未来审查策略变化。
WARP_RS_TRICK="${WARP_RS_TRICK:-none}"
TUNNEL_LOG_VERBOSE="${TUNNEL_LOG_VERBOSE:-0}"

LISTEN_ADDR="0.0.0.0"
LISTEN_PORT="1080"
HOST_LISTEN_ADDR="${HOST_BIND_IP:-127.0.0.1}"
HOST_LISTEN_PORT="${HOST_BIND_PORT:-1080}"

REGISTER_RETRIES="${WARP_SOCKS_REGISTER_RETRIES:-2}"
REGISTER_RETRY_DELAY="${WARP_SOCKS_REGISTER_RETRY_DELAY:-2}"
STARTUP_EGRESS_PROBE_DELAY="${WARP_SOCKS_STARTUP_EGRESS_PROBE_DELAY:-1}"
STARTUP_EGRESS_PROBE_TIMEOUT="${WARP_SOCKS_STARTUP_EGRESS_PROBE_TIMEOUT:-5}"
HEALTHCHECK_PROBE_TIMEOUT="${WARP_SOCKS_HEALTHCHECK_PROBE_TIMEOUT:-4}"
HEALTHCHECK_FAILURE_THRESHOLD="${WARP_SOCKS_HEALTHCHECK_FAILURE_THRESHOLD:-3}"
STARTUP_ENDPOINT_COOLDOWN_SECONDS="30"
STARTUP_SOCKS_READY_TIMEOUT_SECONDS="${WARP_SOCKS_STARTUP_SOCKS_READY_TIMEOUT:-20}"
DEFAULT_ENDPOINT_CANDIDATES="162.159.193.5:2408,162.159.193.9:2408,162.159.193.8:2408,162.159.193.3:2408,162.159.193.7:2408,162.159.193.47:2408,162.159.192.1:2408,162.159.195.1:2408"

HEALTHCHECK_STATE_DIR="/tmp/warp-socks-healthcheck"
HEALTHCHECK_FAIL_COUNT_FILE="${HEALTHCHECK_STATE_DIR}/fail-count"
HEALTHCHECK_RESTART_REQUEST_FILE="${HEALTHCHECK_STATE_DIR}/restart-requested"
HEALTHCHECK_READY_FILE="${HEALTHCHECK_STATE_DIR}/runtime-ready"

LOG_COMPONENT=""
LOG_TIMEZONE_DEFAULT="CST-8"
LOG_TIME_FORMAT_DEFAULT="%Y-%m-%d %H:%M:%S %Z"

TUNNEL_LOG_FILE="/tmp/tunnel.log"
TUNNEL_PID=""
WARP_LOG_TAIL_PID=""
WARP_LOG_RAW_TAIL_PID=""
TUNNEL_WAIT_ATTEMPTS=""
TUNNEL_WAIT_ELAPSED_SECONDS=""
ENDPOINT_SOURCE=""
PROBE_SOCKS_TRACE_REASON=""
PROBE_SOCKS_TRACE_IP=""

RUNTIME_ENDPOINT_COOLDOWN_SECONDS_DEFAULT="60"

normalize_runtime_tuning() {
  REGISTER_RETRIES="$(sanitize_positive_int "$REGISTER_RETRIES" 2)"
  REGISTER_RETRY_DELAY="$(sanitize_nonnegative_int "$REGISTER_RETRY_DELAY" 2)"
  STARTUP_EGRESS_PROBE_DELAY="$(sanitize_nonnegative_int "$STARTUP_EGRESS_PROBE_DELAY" 1)"
  STARTUP_EGRESS_PROBE_TIMEOUT="$(sanitize_positive_int "$STARTUP_EGRESS_PROBE_TIMEOUT" 5)"
  HEALTHCHECK_PROBE_TIMEOUT="$(sanitize_positive_int "$HEALTHCHECK_PROBE_TIMEOUT" 4)"
  HEALTHCHECK_FAILURE_THRESHOLD="$(sanitize_positive_int "$HEALTHCHECK_FAILURE_THRESHOLD" 3)"
  STARTUP_SOCKS_READY_TIMEOUT_SECONDS="$(sanitize_positive_int "$STARTUP_SOCKS_READY_TIMEOUT_SECONDS" 20)"
}

verify_runtime_environment() {
  required_cmds="curl jq wg $WARP_RS_BIN"

  for required_cmd in $required_cmds; do
    command -v "$required_cmd" >/dev/null 2>&1 || fail_tunnel "缺少运行依赖: ${required_cmd}"
  done
}
