#!/bin/sh

WG_DIR="/etc/wireguard"
WG_CONF="${WG_DIR}/wg0.conf"
ACCOUNT_JSON="${WG_DIR}/account.json"
ENDPOINT_STATE_FILE="${WG_DIR}/endpoint-state.json"

REGISTER_URL="https://api.cloudflareclient.com/v0a2158/reg"
CF_CLIENT_VERSION="a-6.10-2158"
TRACE_URL_DEFAULT="https://cloudflare.com/cdn-cgi/trace"
TRACE_IP_URL_DEFAULT="https://1.1.1.1/cdn-cgi/trace"

TEAMS_TOKEN="${TEAMS_TOKEN:-}"
ENDPOINT_CANDIDATES="${ENDPOINT_CANDIDATES:-}"
MICROSOCKS_LOG_ACCESS="${MICROSOCKS_LOG_ACCESS:-1}"
MICROSOCKS_LOG_LOCAL_CLIENTS="${MICROSOCKS_LOG_LOCAL_CLIENTS:-0}"

LISTEN_ADDR="0.0.0.0"
LISTEN_PORT="1080"
HOST_LISTEN_ADDR="${HOST_BIND_IP:-127.0.0.1}"
HOST_LISTEN_PORT="${HOST_BIND_PORT:-1080}"

REGISTER_RETRIES="${WARP_SOCKS_REGISTER_RETRIES:-2}"
REGISTER_RETRY_DELAY="${WARP_SOCKS_REGISTER_RETRY_DELAY:-2}"
STARTUP_EGRESS_PROBE_RETRIES="${WARP_SOCKS_STARTUP_EGRESS_PROBE_RETRIES:-2}"
STARTUP_EGRESS_PROBE_DELAY="${WARP_SOCKS_STARTUP_EGRESS_PROBE_DELAY:-1}"
STARTUP_EGRESS_PROBE_TIMEOUT="${WARP_SOCKS_STARTUP_EGRESS_PROBE_TIMEOUT:-3}"
HEALTHCHECK_PROBE_TIMEOUT="${WARP_SOCKS_HEALTHCHECK_PROBE_TIMEOUT:-4}"
HEALTHCHECK_FAILURE_THRESHOLD="${WARP_SOCKS_HEALTHCHECK_FAILURE_THRESHOLD:-3}"
STARTUP_ENDPOINT_COOLDOWN_SECONDS="30"
DEFAULT_ENDPOINT_CANDIDATES="162.159.193.5:2408,162.159.193.9:2408,162.159.193.8:2408,162.159.193.3:2408,162.159.193.7:2408"

LOCAL_BYPASS_RULE_PRIORITY_FALLBACK=97
LOCAL_BYPASS_IPV4_SUBNETS="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10,169.254.0.0/16"
LOCAL_BYPASS_IPV6_SUBNETS="fc00::/7,fe80::/10"

HEALTHCHECK_STATE_DIR="/tmp/warp-socks-healthcheck"
HEALTHCHECK_FAIL_COUNT_FILE="${HEALTHCHECK_STATE_DIR}/fail-count"
HEALTHCHECK_RESTART_REQUEST_FILE="${HEALTHCHECK_STATE_DIR}/restart-requested"
HEALTHCHECK_READY_FILE="${HEALTHCHECK_STATE_DIR}/runtime-ready"

LOG_COMPONENT=""
LOG_TIMEZONE_DEFAULT="CST-8"
LOG_TIME_FORMAT_DEFAULT="%Y-%m-%d %H:%M:%S %Z"
LOG_MODE_DEFAULT="teams"

FORMATTED_LOG_PIPE=""
FORMATTED_LOG_READER_PID=""
MICROSOCKS_PID=""
ENDPOINT_SOURCE=""
PROBE_DIRECT_TRACE_REASON=""
PROBE_DIRECT_TRACE_IP=""

RUNTIME_ENDPOINT_COOLDOWN_SECONDS_DEFAULT="60"

normalize_runtime_tuning() {
  case "$REGISTER_RETRIES" in
    ''|*[!0-9]*|0) REGISTER_RETRIES="2" ;;
  esac
  case "$REGISTER_RETRY_DELAY" in
    ''|*[!0-9]*) REGISTER_RETRY_DELAY="2" ;;
  esac
  case "$STARTUP_EGRESS_PROBE_RETRIES" in
    ''|*[!0-9]*|0) STARTUP_EGRESS_PROBE_RETRIES="2" ;;
  esac
  case "$STARTUP_EGRESS_PROBE_DELAY" in
    ''|*[!0-9]*) STARTUP_EGRESS_PROBE_DELAY="1" ;;
  esac
  case "$STARTUP_EGRESS_PROBE_TIMEOUT" in
    ''|*[!0-9]*|0) STARTUP_EGRESS_PROBE_TIMEOUT="3" ;;
  esac
  case "$HEALTHCHECK_PROBE_TIMEOUT" in
    ''|*[!0-9]*|0) HEALTHCHECK_PROBE_TIMEOUT="4" ;;
  esac
  case "$HEALTHCHECK_FAILURE_THRESHOLD" in
    ''|*[!0-9]*|0) HEALTHCHECK_FAILURE_THRESHOLD="3" ;;
  esac
}

# 未来迁移到编译型语言时，可直接映射成 trait 边界：
# - account_*     -> AccountRegistry
# - endpoint_*    -> EndpointPlanner
# - tunnel_*      -> TunnelManager
# - socks_*       -> SocksRuntime
# - recovery_*    -> RecoveryCoordinator
